name: Docker Build and Push

on:
  push:
    branches:
      - "main"

jobs:
  call-docker-build-push:
    uses: submitty/action-docker-build/.github/workflows/docker-build-push.yml@v24.06.00
    with:
      push: true
      docker_username: ${{ vars.docker_username }}
      base_commit: ${{ github.event.before }}
      head_commit: ${{ github.event.after }}
    secrets:
      docker_password: ${{ secrets.docker_password }}
